Add ISP 3A camera controls
luxonis/depthai pull request #209
Opened 2020-09-28 22:16 UTC by alex-luxonis

Please check the source code changes in https://github.com/luxonis/depthai-python/pull/52

Temporary note: need to wait for the checks on the above PR to be completed before it can be used.

2020-09-28 23:03 UTC, szabi-luxonis requested changes

2020-09-28 23:03 UTC, szabi-luxonis commented on depthai_demo.py
> +            elif key == ord('5'):
create a lookup table (dictionary) for all these ISP commands, so it's easier to add/remove and the code is cleaner.
In `DepthAI` class:
```
    def keypress_handler(self, cmd):

        keypress_handler_lut = {
            ord('f'): lambda: self.device.request_af_trigger()
       . 
       . 
       .
        }
        if cmd in keypress_handler_lut:
            keypress_handler_lut[cmd]()
        return
```

instead the elif's : 
`self.keypress_handler(key)`

2020-10-07 15:38 UTC, szabi-luxonis approved these changes

2020-10-07 16:08 UTC, Luxonis-Brandon commented
Sweet, this will be nice to get into develop.  Thanks, all!

2020-10-07 22:15 UTC, merged