depthai_demo UI and visualisation improvements. Ref #358
luxonis/depthai pull request #364
Opened 2021-05-05 13:28 UTC by dhruvsheth-ai

Changed branch to Main. Refer - https://github.com/luxonis/depthai/pull/358

2021-05-09 21:54 UTC, VanDavv requested changes
@dhruvsheth-ai I think something has gone wrong during the merge, as it seems that this PR would revert some of the changes we added to `main` recently.

2021-05-09 21:54 UTC, VanDavv commented on depthai_demo.py
> -        self.timestamp = time.monotonic()
we should stick to `monotonic`

2021-05-09 21:54 UTC, VanDavv commented on depthai_demo.py
> -print('Using depthai module from: ', dai.__file__)
This should stay

2021-05-09 21:54 UTC, VanDavv commented on depthai_demo.py
> +conf.adjustParamsToDevice()
and this shouldn't be added here

2021-05-12 16:59 UTC, dhruvsheth-ai commented
Is the updated file fine now @VanDavv ? The UI changes have been redone on the updated depthai_demo.py script.

2021-05-18 11:03 UTC, VanDavv approved these changes

2021-05-18 11:06 UTC, VanDavv commented
Thanks @dhruvsheth-ai!

2021-05-18 11:06 UTC, merged