Host video sync
luxonis/depthai pull request #372
Opened 2021-05-14 15:40 UTC by Erol444

added sync functionality when sending video from the host

2021-05-18 09:37 UTC, VanDavv requested changes

2021-05-18 09:37 UTC, VanDavv commented on depthai_demo.py
> +        conf.args.show = ["host"]
I would move this to adjustPreviewToOptions - https://github.com/luxonis/depthai/blob/1f2244c75a660272bdef15f1865a4fda8b3fcd6a/depthai_helpers/config_manager.py#L184

2021-05-18 09:37 UTC, VanDavv commented on depthai_demo.py
> +                if self.nn_manager.source in ["color", "host"] and hasattr(self.nodes, "xout_rgb"):
I wouldn't like to mix xout_rgb to send the host frames. Let's add another if condition and check for `xout_host` (which we create prior)

2021-05-18 09:37 UTC, VanDavv commented on depthai_demo.py
> +                nodes.xout_rgb = p.createXLinkOut()
```suggestion
                nodes.xout_host = p.createXLinkOut()
```

2021-05-18 09:37 UTC, VanDavv commented on depthai_demo.py
> +                nodes.xout_rgb.setStreamName("host")
Let's add a `host` to Previews - https://github.com/luxonis/depthai/blob/1f2244c75a660272bdef15f1865a4fda8b3fcd6a/depthai_demo.py#L59 and use `Previews.host.name` as a stream name

2021-05-18 09:37 UTC, VanDavv commented on depthai_demo.py
> +                host_frame_in = np.array(pv.output_queues[0].get().getData()).reshape((3, in_h, in_w)).transpose(1, 2, 0).copy()
this should be updated in `prepare_frames` of PreviewManager

2021-05-19 11:42 UTC, VanDavv commented
Updated, testable using

```
depthai_demo.py -sync -vid https://www.youtube.com/watch?v=Y1jTEyb3wiI
```

2021-05-19 11:45 UTC, VanDavv approved these changes

2021-05-19 11:45 UTC, merged

2021-05-20 21:52 UTC, cafemoloko commented on depthai_demo.py
> +                    print("Received NN packet: <Preview unabailable: {}>".format(ex))
@VanDavv, typo in word _unavailable_