Added issue template for feature request
luxonis/depthai pull request #374
Opened 2021-05-15 22:46 UTC by Erol444

Added issue template for a feature request.

Should we have any other title, like `[ENHANCEMENT]`?

2021-05-16 00:13 UTC, Luxonis-Brandon commented
Yes I think that’s a good idea.

2021-05-18 11:19 UTC, szabi-luxonis requested changes

2021-05-18 11:19 UTC, szabi-luxonis commented on .github/ISSUE_TEMPLATE/feature_request.md
> +title: "[Feature-Request]"
Add also `{Title of feature request}`.
Same for BUG template.
People tend to leave it as it is, with no distinguishable title.

2021-05-28 02:12 UTC, szabi-luxonis approved these changes

2021-05-28 08:44 UTC, merged