Added object counting feature
luxonis/depthai pull request #400
Opened 2021-06-17 10:36 UTC by Erol444

`python3.6 depthai_demo.py --count 5`
![image](https://user-images.githubusercontent.com/18037362/122380531-42d90780-cf68-11eb-94c7-6db80ab8e36c.png)

`python3.6 depthai_demo.py --count tvmonitor`
![image](https://user-images.githubusercontent.com/18037362/122380547-48365200-cf68-11eb-8b73-698bdd9a86b0.png)

I'm using bottles as an example because the model detects them accurately. 
Any ideas on how to get multiples of the object? So it would display eg. `2 people` instead of `2 person`

2021-06-17 17:49 UTC, Luxonis-Brandon commented
Looks great!

2021-06-18 10:28 UTC, VanDavv requested changes

2021-06-18 10:28 UTC, VanDavv commented on depthai_demo.py
> +        self.count = conf.getCountLabel(self)
Can we rename the self.count and conf.args.count to `count_label`? 

The cli param can stay the same, adding `dest` flag to argparse should make it work, it's only a matter of knowing that does a count variable mean

2021-06-18 10:28 UTC, VanDavv commented on depthai_demo.py
> +                cnt_iter = filter(lambda x: self.get_label_text(x.label) == self.count, decoded_data)
```suggestion
                cnt_iter = list(filter(lambda x: self.get_label_text(x.label) == self.count, decoded_data))
```

2021-06-18 10:28 UTC, VanDavv commented on depthai_demo.py
> +                cnt = sum(1 for _ in cnt_iter)
```suggestion
                cnt = len(cnt_iter)
```

2021-06-18 10:28 UTC, VanDavv commented on depthai_demo.py
> +                cnt_iter = filter(lambda x: self.get_label_text(x.label) == self.count, decoded_data)
And it would also change it's name from `cnt_iter` to `cnt_list` or other

2021-06-18 10:28 UTC, VanDavv commented on depthai_helpers/arg_manager.py
> +    parser.add_argument("--count", type=str, help="Count and display the number of specified objects on the frame. You have to specify the object (label) you want to count.")
I would add that the label can be either a label id or label name (if defined labels in nn config file)

2021-06-21 09:11 UTC, VanDavv approved these changes

2021-06-21 09:19 UTC, merged