OAK-D Pro support
luxonis/depthai pull request #556
Opened 2021-11-29 16:25 UTC by alex-luxonis

The IR LED and laser projector are disabled by default, but can be controlled through a GUI when running `depthai_demo.py`.
See here for possible setups:
https://github.com/luxonis/depthai-hardware/issues/114#issuecomment-946950571
Note though that protection glasses must be used when operating the device, as no intensity limits are applied yet in firmware.

The branches `oak-d-pro` from [depthai-python](https://github.com/luxonis/depthai-python/compare/multi_cam_support...oak-d-pro) and [depthai-core](https://github.com/luxonis/depthai-core/compare/multi_cam_support...oak-d-pro) can also be used, but the entire IR driver initialization sequence have to be set. It can be obtained when running `depthai_demo.py` which prints each raw I2C register write for LM3644.
```
dev.irWriteReg(0x2, 0x1)
dev.irWriteReg(0x3, 0x0)
dev.irWriteReg(0x4, 0x0)
dev.irWriteReg(0x5, 0x0)
dev.irWriteReg(0x6, 0x0)
dev.irWriteReg(0x7, 0x9)
dev.irWriteReg(0x8, 0x1a)
dev.irWriteReg(0x9, 0x8)
dev.irWriteReg(0x1, 0x24) 
# Init done, TODO control brightness here, for example:
dev.irWriteReg(0x04, 40)
```
An easier to use API for setting each function will be added later.

2022-01-26 07:30 UTC, Luxonis-David requested changes
Small change in revision

2022-01-26 07:30 UTC, Luxonis-David commented on resources/boards/OAK-D-PRO-W.json
> +        "revision": "R2M1E2",
```suggestion
        "revision": "R3M1E3",
```

2022-01-26 07:30 UTC, Luxonis-David commented on resources/boards/OAK-D-PRO.json
> +        "revision": "R2M1E2",
```suggestion
        "revision": "R3M1E3",
```

2022-02-24 11:56 UTC, alex-luxonis commented
Support for OAK-D Pro is available in mainline with the `2.15.0.0` release (not formally released yet, but can be installed now).
The demo was updated to use the new IR driver control API (only the CV GUI part for now).

Can be tested with:
`python3 depthai_demo.py -gt cv -s color left right depth`
`python3 depthai_demo.py -gt cv -s color left right depth -lrc`
Extra controls will appear in the `depth` window:
![image](https://user-images.githubusercontent.com/60824841/155518968-aec0c7fc-9602-423d-a0a5-a758ccecab5c.png)

Note: the color camera (OV9782) on OAK-D-Pro-W-DEV is not supported yet, and a separate branch will still be needed (to be updated).

2022-02-25 17:10 UTC, Erol444 approved these changes
Tested it out with OAK-D-Pro and it works as expected :+1:

2022-02-25 18:14 UTC, VanDavv approved these changes
I added `--irDotBrightness` and `--irFloodBrightness` parameters and I think it's ready to be merged now @alex-luxonis

2022-02-25 20:03 UTC, alex-luxonis commented
Updated the PR description.

2022-02-25 21:00 UTC, merged