Sdk tutorial
luxonis/depthai pull request #659
Opened 2022-03-17 09:26 UTC by ZigiMigi

2022-03-18 08:49 UTC, VanDavv requested changes
Thanks! They look great! 
I left some comments but overall this is a very good starting point we can iterate further

2022-03-18 08:49 UTC, VanDavv commented on depthai_sdk/docs/source/blob_nnet_manager.rst
> +.. include::  blob_projects.rst
@ZigiMigi BlobManager supports all models in both [Open Model Zoo](https://github.com/openvinotoolkit/open_model_zoo) and [our model zoo](https://github.com/luxonis/depthai-model-zoo). 
By using `configPath` you can download any arbitrary model and `zooDir` param you can specify a path to a custom model zoo as well (which can contain both already compiled blobs and model yml files)

BlobManager is able to both reuse existing blobs, download models from model zoo and compile custom models based on yml config

2022-03-18 08:49 UTC, VanDavv commented on depthai_sdk/docs/source/blob_nnet_manager.rst
> +``Blob manager`` is a class that is made to help you with setting up neural networks.
typo, nnet manager. This description should be extended, as NNetManager is responsible for all NN-related efforts, including creating a correct pipeline as well as drawing nn results on frames

2022-03-18 08:49 UTC, VanDavv commented on depthai_sdk/docs/source/blob_nnet_manager.rst
> +As the ``Blob manager`` and ``Nnet manager`` work together, we will need both to use our neural network. We will also need to use the ``Pipeline manager`` and the ``Preview manager`` to make everythi
This is false, as BlobManager and NNetManager can (and often are) used separately. 
BlobManager is useful if you want to have the ability to download models based on model config or custom model zoo.
Nnet Manager only requires blob path, which can be provided both from BlobManager but also directly from `blobconverter` module.

I often do `blobPath=blobconverter.from_zoo(...)` as it's simpler

2022-03-18 08:49 UTC, VanDavv commented on depthai_sdk/docs/source/blob_nnet_manager.rst
> +As the ``Blob manager`` and ``Nnet manager`` work together, we will need both to use our neural network. We will also need to use the ``Pipeline manager`` and the ``Preview manager`` to make everythi
Regarding PipelineManager and PreviewManager connections:
- PipelineManager is able to integrate with `NNetManager`, as it's needed to both add neural network node to the pipeline (`addNN` method) and we need to sync OpenVINO version between nn and pipeline (hence `setNnManager` method). This is one way sync and is mostly optional
- NNetManager is able to integrate with PreviewManager for convenience, but it's also able to parse raw frames passed to it.

With the comments above, my point is that we should show our users that these manager/helper classes are flexible and modular, allowing to pick only the ones you find most suitable

2022-03-18 08:49 UTC, VanDavv commented on depthai_sdk/docs/source/blob_nnet_manager.rst
> +Every project has its own ``inputSize`` and ``familyName``. To see more about the different requirements check the ``depthai/resources/nn`` folder. Every blob has its requirements in it's json file.
`depthai/respources/nn` are specific to depthai demo, it's also not needed when dealing with mobilenet-ssd-based networks (like the one you used), all parameters can be supplied on init.
Maybe nitpicking, but these json files store decoding config, not actual requirements

2022-03-18 08:49 UTC, VanDavv commented on depthai_sdk/docs/source/encoding_manager.rst
> +The most important part, when using the ``Encoding manager`` is that the encoder must be initialized before the pipeline.
Encoder must be created during pipeline creation, as it adds nodes to the pipeline that gets later executed. So it's best to create encoding manager after PipelineManager, but before sending it to the device

2022-03-18 08:49 UTC, VanDavv commented on depthai_sdk/docs/source/examples/camera_preview.py
> +    pv = PreviewManager(display=[Previews.color.name, Previews.left.name, Previews.right.name, Previews.depthRaw.name])
I think it's better to use `depth` instead of `depthRaw`, as it looks better

2022-03-18 08:49 UTC, VanDavv commented on depthai_sdk/docs/source/examples/code_fractions/encoder.py
> +em = EncodingManager(encodeConfig, Path(""))
please use `Path(__file__)`

2022-03-18 08:49 UTC, VanDavv commented on depthai_sdk/docs/source/examples/code_fractions/previews.py
> +    pv.prepareFrames()
this needs to be in a loop

2022-03-25 16:34 UTC, VanDavv requested changes
Overall it's a very good direction, thanks @ZigiMigi !

2022-03-25 16:34 UTC, VanDavv commented on depthai_sdk/docs/source/nnet_manager.rst
> +This example shows how to use the ``mobile net`` project. The code should be almost the same as the one that we used in the above example, with the only difference being
Full name of this network is `MobileNetSSD`

2022-03-25 16:34 UTC, VanDavv commented on depthai_sdk/docs/source/pipeline_manager.rst
> +Pipeline is the first class that we will learn how to use as it is the one that is goes hand in hand with every other class.
*PipelineManager

2022-03-25 16:34 UTC, VanDavv commented on depthai_sdk/docs/source/preview_manager.rst
> +But of course you will also have to import bot names to use them.
*both

2022-03-25 16:49 UTC, ZigiMigi commented on depthai_sdk/docs/source/indexNEW.rst
> +================================
We do not actualy, I just left the old index (the one that was beeing used before i started working on this) and made the new one as indexNew.

2022-03-28 18:27 UTC, VanDavv requested changes
Just one thing left, otherwise looks great!

2022-03-28 18:27 UTC, VanDavv commented on depthai_sdk/docs/source/index.rst
> +In this tutorial, we’ll show you how to use DepthAI SDK for a couple of basic use cases, that can give you an overall idea how to use it and in which cases it might be useful.
The index page is not a tutorial, you can move this header to tutorial page

2022-03-31 11:29 UTC, merged