Add temperature shutdown
luxonis/depthai pull request #665
Opened 2022-03-21 10:47 UTC by VanDavv

This PR adds a temperature shutdown mechanism that raises Overheat error if the device gets over 105* celsius

2022-03-21 15:00 UTC, themarpe commented on depthai_demo.py
> +            if temperature.average > 100:
Modify to any temp reading > 105.0C

2022-03-21 15:01 UTC, themarpe commented
I assume you've raised the OverheatError specifically so that Sentry will pick it up as is, correct?

2022-03-23 18:24 UTC, VanDavv commented
Yes, also custom exception can be caught by users who extend the demo further (not to raise a regular RuntimeError when we can distinguish this error)

2022-03-24 08:24 UTC, themarpe requested changes

2022-03-24 08:24 UTC, themarpe commented on depthai_demo.py
> +            if temperature.average > 105:
Check if any temperatures is higher than 105C, otherwise it might trigger too late

2022-03-24 15:22 UTC, themarpe approved these changes

2022-03-24 15:28 UTC, merged