Eeprom v7 flash update in conalibrati
luxonis/depthai pull request #707
Opened 2022-05-31 18:23 UTC by saching13

2022-05-31 18:49 UTC, szabi-luxonis requested changes

2022-05-31 18:49 UTC, szabi-luxonis commented on calibrate.py
> +            calibration_handler = self.device.readCalibration2()
Bump depthai to 2.15.5.0 in requirements

2022-05-31 20:03 UTC, themarpe requested changes

2022-05-31 20:03 UTC, themarpe commented on calibrate.py
> +            calibration_handler = self.device.readCalibration2()
readCalibration2 throws if EEPROM is empty. Make sure to catch / notify / handle that case.
Also, make sure to flash both USER & FACTORY sections and compare those to be equal

2022-06-01 13:15 UTC, Erol444 commented
@saching13 I also created a branch for that; https://github.com/luxonis/depthai/pull/708 Maybe we could use that, as it will flash name/revision only if it's empty? It was also [tested by one user](https://discord.com/channels/790680891252932659/924798475030392922/980828130858127421).

2022-06-01 16:04 UTC, saching13 commented
> @saching13 I also created a branch for that; #708 Maybe we could use that, as it will flash name/revision only if it's empty? It was also [tested by one user](https://discord.com/channels/790680891252932659/924798475030392922/980828130858127421).

Sounds good. @Erol444  do you want to make that PR or should I import them here and wrap it up ?

2022-06-02 13:03 UTC, themarpe reviewed
Is the "factory flashing" limited to factory devices? Or do you intend to user expose it? @saching13

2022-06-04 00:06 UTC, themarpe requested changes
`readCalibration2` could be used instead of having to cross check "default" calibration returned by `readCalibration` against it being empty.

Otherwise lgtm

2022-06-09 23:19 UTC, themarpe approved these changes

2022-06-10 00:13 UTC, merged